#quiet: yes
timeout: 1
default_entry: 1
remember_last_entry: yes

# CachyOS Limine theme
# Author: diegons490 (https://github.com/diegons490/cachyos-limine-theme)
term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_background: ffffffff
term_foreground: cdd6f4
term_background_bright: ffffffff
term_foreground_bright: cdd6f4
interface_branding:
wallpaper: boot():/limine-splash.png

# For Lenovo IdeaPad Duet 5i
interface_rotation: 90
cmdline: nowatchdog relatime rw fbcon=rotate:1 video=DSI-1:panel_orientation=right_side_up rootflags=subvol=/@ root=UUID=IKRAM-GANTENG-BUSET

# For Steam Deck
interface_rotation: 90
cmdline: nowatchdog relatime rw fbcon=rotate:1 video=DSI-1:panel_orientation=right_side_up rootflags=subvol=/@ root=UUID=IKRAM-GANTENG-BUSET
